### ISSUE TITLE
'matio' CMake Error

### ISSUE THREAD

**Issue by hecperleo** [larics/lattice_planner#6]
> -- Checking for one of the modules 'matio'
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:578 (message):
  None of the required 'matio' found
Call Stack (most recent call first):
  lattice_planner/CMakeLists.txt:18 (pkg_search_module)

If i try to use catkin_make i receive this error. After that i get CMake Warning and i guess that i should not be worry about those. 

By the way, https://github.com/larics/lattice_navigation_demos  has a wrong URL in "lattice_planner" it goes to agv_control_msg repository.

**Comment by dmiklic** [comment]
Thanks for the quick feedback. You need to install the matio library before running catkin:
```
sudo apt install libmatio-dev
```
I have updated the installation instructions to mention this in be74979d24b91812b71f973ad899223cfa102641
